### ISSUE TITLE
Compiling issue on macOS 11.4 with Clang 12.0.5

### ISSUE THREAD

**Issue by JasonRuonanWang** [robertu94/libpressio#17]
I had these errors when I was trying to compile LibPressio on Mac systems. 

[ 81%] Building CXX object CMakeFiles/libpressio.dir/src/plugins/io/copy_template.cc.o
In file included from /Users/jason/d/src/libpressio/src/plugins/compressors/transpose.cc:5:
In file included from /Users/jason/d/src/libpressio/include/libpressio_ext/cpp/data.h:12:
/Users/jason/d/src/libpressio/include/libpressio_ext/cpp/dtype.h:28:3: error: static_assert failed due to requirement 'impl::is_one_of<unsigned long, double, float, signed char, short, int, long long, unsigned char, unsigned short, unsigned int, unsigned long long>::value' "unexpected type"
  static_assert(impl::is_one_of<T,double, float, int8_t, int16_t, int32_t, int64_t, uint8_t, uint16_t, uint32_t, uint64_t>::value, 
  ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jason/d/src/libpressio/include/libpressio_ext/cpp/data.h:461:16: note: in instantiation of function template specialization 'pressio_dtype_from_type<unsigned long>' requested here
    data_dtype(pressio_dtype_from_type<typename std::iterator_traits<ForwardIt>::value_type>()),
               ^
/Users/jason/d/src/libpressio/src/plugins/compressors/transpose.cc:21:36: note: in instantiation of function template specialization 'pressio_data::pressio_data<std::__1::__wrap_iter<const unsigned long *>>' requested here
    set(options, "transpose:axis", pressio_data(axis.begin(), axis.end()));
                                   ^
In file included from /Users/jason/d/src/libpressio/src/plugins/compressors/resize.cc:5:
In file included from /Users/jason/d/src/libpressio/include/libpressio_ext/cpp/data.h:12:
/Users/jason/d/src/libpressio/include/libpressio_ext/cpp/dtype.h:28:3: error: static_assert failed due to requirement 'impl::is_one_of<unsigned long, double, float, signed char, short, int, long long, unsigned char, unsigned short, unsigned int, unsigned long long>::value' "unexpected type"
  static_assert(impl::is_one_of<T,double, float, int8_t, int16_t, int32_t, int64_t, uint8_t, uint16_t, uint32_t, uint64_t>::value, 
  ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jason/d/src/libpressio/include/libpressio_ext/cpp/data.h:461:16: note: in instantiation of function template specialization 'pressio_dtype_from_type<unsigned long>' requested here
    data_dtype(pressio_dtype_from_type<typename std::iterator_traits<ForwardIt>::value_type>()),
               ^
/Users/jason/d/src/libpressio/src/plugins/compressors/resize.cc:22:44: note: in instantiation of function template specialization 'pressio_data::pressio_data<std::__1::__wrap_iter<const unsigned long *>>' requested here
    set(options, "resize:compressed_dims", pressio_data(compressed_dims.begin(), compressed_dims.end()));
                                           ^
1 error generated.
make[2]: *** [CMakeFiles/libpressio.dir/src/plugins/compressors/transpose.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 error generated.
make[2]: *** [CMakeFiles/libpressio.dir/src/plugins/compressors/resize.cc.o] Error 1
/Users/jason/d/src/libpressio/src/plugins/metrics/region_of_interest.cc:31:13: error: no viable overloaded '='
        end = input_dims;
        ~~~ ^ ~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/vector:562:13: note: candidate function not viable: no known conversion from 'const vector<size_t, allocator<unsigned long>>' to 'const vector<unsigned long long, allocator<unsigned long long>>' for 1st argument
    vector& operator=(const vector& __x);
            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/vector:582:13: note: candidate function not viable: no known conversion from 'const vector<size_t, allocator<unsigned long>>' to 'vector<unsigned long long, allocator<unsigned long long>>' for 1st argument
    vector& operator=(vector&& __x)
            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/vector:586:13: note: candidate function not viable: no known conversion from 'const std::vector<size_t>' (aka 'const vector<unsigned long>') to 'initializer_list<std::__1::vector<unsigned long long>::value_type>' (aka 'initializer_list<unsigned long long>') for 1st argument
    vector& operator=(initializer_list<value_type> __il)
            ^
1 error generated.
make[2]: *** [CMakeFiles/libpressio.dir/src/plugins/metrics/region_of_interest.cc.o] Error 1

**Comment by robertu94** [comment]
@JasonRuonanWang can you please confirm the LibPressio version number?  It should be in CMakeLists.txt. I'll look at this soon.

**Comment by JasonRuonanWang** [comment]
@robertu94 I was just using the latest master. Do you have a specific version that you recommend?

**Comment by robertu94** [comment]
I just want the commit hash to verify I am using the same commit.

**Comment by JasonRuonanWang** [comment]
libpressio VERSION "0.60.0"

commit e1bc0343a9a4ca4075adc0612f837065fe9cc284 (HEAD -> master, origin/master, origin/HEAD)
Author: Robert Underwood <rr.underwood94@gmail.com>
Date:   Wed Mar 17 12:10:50 2021 -0400

    Add documentation to python bindings
    
    No changes to libpressio

**Comment by robertu94** [comment]
@JasonRuonanWang You're running a slightly older version. My development version can be found here. Can you give it a shot?

https://github.com/robertu94/libpressio

**Comment by JasonRuonanWang** [comment]
I have got another error by compiling this version 

[ 75%] Building CXX object CMakeFiles/libpressio.dir/src/plugins/io/empty.cc.o
/Users/jason/d/src/libpressio/src/plugins/io/numpy.cc:47:21: error: implicit instantiation of undefined template 'std::__1::basic_stringstream<char>'
  std::stringstream shape;
                    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/iosfwd:139:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_stringstream;
                               ^
/Users/jason/d/src/libpressio/src/plugins/io/numpy.cc:60:21: error: implicit instantiation of undefined template 'std::__1::basic_stringstream<char>'
  std::stringstream format;
                    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/iosfwd:139:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_stringstream;
                               ^
/Users/jason/d/src/libpressio/src/plugins/io/numpy.cc:100:21: error: implicit instantiation of undefined template 'std::__1::basic_stringstream<char>'
  std::stringstream header;
                    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/iosfwd:139:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_stringstream;
                               ^
3 errors generated.
make[2]: *** [CMakeFiles/libpressio.dir/src/plugins/io/numpy.cc.o] Error 1

**Comment by robertu94** [comment]
@JasonRuonanWang I just updated the repo on my development version to 0.66.2 which I think should fix this.  Could you please give it a shot?

**Comment by JasonRuonanWang** [comment]
@robertu94 It did fix the problem. Thanks very much.
