### ISSUE TITLE
Libpressio not building for C++ compiler

### ISSUE THREAD

**Issue by hgerrald** [robertu94/libpressio#2]
# Description
To begin, the #include <libpressio.h> is causing an error in my .cpp file, and I believe it is because I have not built libpressio for the C++ compiler. I think the command 

> cmake -DLIBPRESSIO_CXX_VERSION=11

actually needs a .. after CMake, and once I insert that it runs fine. The make command, however, is failing. My error is shown in the image below. 
![cmake_c++_error](https://user-images.githubusercontent.com/32804403/73081638-fafaa180-3e95-11ea-9880-af3312a3ae50.png)

# Versions and Configuration

Contents of `/etc/os-release`:
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

Output of `cmake -L $BUILD_DIR`:
-- Checking for transform_reduce: FALSE
-- Checking for exclusive_scan: FALSE
-- Checking for exchange: FALSE
-- Checking for rbeginend: FALSE
-- Checking for optional: FALSE
-- Checking for variant: FALSE
-- Checking for make_unique: FALSE
-- Checking for conjunction: FALSE
-- Checking for multiplies: FALSE
-- Boost version: 1.65.1
-- Checking for Magick::LongLong: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /home/heath/libpressio/build/test/googletest-download
[ 11%] Performing update step for 'googletest'
Current branch master is up to date.
[ 22%] No configure step for 'googletest'
[ 33%] No build step for 'googletest'
[ 44%] No install step for 'googletest'
[ 55%] No test step for 'googletest'
[ 66%] Completed 'googletest'
[100%] Built target googletest
-- Configuring done
-- Generating done
-- Build files have been written to: /home/heath/libpressio/build
-- Cache values
BUILD_DOCKER_CONTAINERS:BOOL=OFF
BUILD_DOCS:BOOL=ON
BUILD_GMOCK:BOOL=ON
BUILD_PYTHON_WRAPPER:BOOL=ON
BUILD_SHARED_LIBS:BOOL=ON
BUILD_TESTING:BOOL=ON
CMAKE_BUILD_TYPE:STRING=Release
CMAKE_INSTALL_PREFIX:PATH=/usr/local
INSTALL_GTEST:BOOL=ON
LIBPRESSIO_HAS_BLOSC:BOOL=true
LIBPRESSIO_HAS_FPZIP:BOOL=OFF
LIBPRESSIO_HAS_HDF:BOOL=OFF
LIBPRESSIO_HAS_MAGICK:BOOL=true
LIBPRESSIO_HAS_MGARD:BOOL=true
LIBPRESSIO_HAS_SZ:BOOL=true
LIBPRESSIO_HAS_ZFP:BOOL=true
Python_NumPy_INCLUDE_DIR:PATH=/usr/local/lib/python3.6/dist-packages/numpy/core/include
SWIG_EXECUTABLE:FILEPATH=/usr/bin/swig3.0
SZ_DIR:PATH=/usr/local/share/SZ/cmake
USE_CLANG_TIDY:BOOL=OFF
ZFP_DIR:PATH=/usr/local/lib/cmake/zfp
mgard_DIR:PATH=/usr/local/lib/cmake/mgard

Output of `git log -n 1 --oneline`:
cb1d35a (HEAD -> master, origin/master, origin/HEAD) Add issue template and bug reporting info

Please include the version information for the following dependencies if installed.

+ compiler either `gcc` or `clang`
gcc version 7.4.0 
clang version 7.0.0-3
+ cmake
cmake version 3.14.6
+ `Doxygen` 
1.8.18 (f8c32f996cac5db890c29958989d25ada389772b)
+ `HDF5` 

+ `ImageMagick` 
Version: ImageMagick 7.0.9-14
+ `blosc` 
+ `boost` 
1.65.1.0ubuntu1
+ `numpy` 
1.18.1
+ `swig` 
SWIG Version 3.0.12
+ `sz` 
version: 2.1.8
+ `zfp` 

# Steps to Reproduce the Bug

Please provide both:

I have built libpressio and with the Python bindings using CMake and it works fine. However, when trying to build for C++ usage it will not make. I can try to create a docker file if necessary, but I think it has something to do with make_unique being false and I'm not sure how to turn it on.

# Additional Information [Optional]

**Comment by robertu94** [comment]
This issue was resolved in version 0.27.1; please update.
